// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailNotifier is an autogenerated mock type for the EmailNotifier type
type EmailNotifier struct {
	mock.Mock
}

// StockChanged provides a mock function with given fields: oldStock, newStock, email
func (_m *EmailNotifier) StockChanged(oldStock int, newStock int, email string) string {
	ret := _m.Called(oldStock, newStock, email)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, int, string) string); ok {
		r0 = rf(oldStock, newStock, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
